import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Behavioral Evidence Report — RecruitOS",
  description:
    "AI-assisted behavioral evidence and alignment report. Candidate decision support generated by RecruitOS.",
  robots: "noindex", // Don't index shared reports
};

/**
 * Standalone layout for the shareable report page.
 * No Header, Footer, or app chrome — clean report view.
 */
export default function ReportLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
