export const RECRUITOS_PRICING_PLANS = [
  {
    id: "starter",
    name: "Starter",
    tagline: "Prøv platformen med et lille kredit-pakke",
    credits: 10,
    price: 500,
    pricePerCredit: 50,
    currency: "DKK",
    period: "one-time",
    features: [
      "10 kandidat-analyser",
      "AI-drevet profilanalyse",
      "Adfærdsindsigter",
      "E-mail support",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    tagline: "Til teams med løbende rekruttering",
    credits: 50,
    price: 2000,
    pricePerCredit: 40,
    currency: "DKK",
    period: "one-time",
    popular: true,
    features: [
      "50 kandidat-analyser",
      "AI-drevet profilanalyse",
      "Adfærdsindsigter",
      "Dybe profiler med GitHub-analyse",
      "Prioriteret support",
      "CSV-eksport",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    tagline: "Til store organisationer",
    credits: 200,
    price: 5000,
    pricePerCredit: 25,
    currency: "DKK",
    period: "one-time",
    features: [
      "200 kandidat-analyser",
      "AI-drevet profilanalyse",
      "Adfærdsindsigter",
      "Dybe profiler med GitHub-analyse",
      "Team-arbejdsrum",
      "API-adgang",
      "Dedikeret account manager",
      "ATS-integration",
    ],
  },
  {
    id: "annual",
    name: "Årligt Ubegrænset",
    tagline: "Ubegrænset adgang hele året",
    credits: "unlimited",
    price: 30000,
    pricePerCredit: null,
    currency: "DKK",
    period: "annual",
    features: [
      "Ubegrænset kandidat-analyser",
      "Alt i Enterprise-pakken",
      "Ubegrænsede team-pladser",
      "Prioriteret 24/7 support",
      "Custom integrationer",
      "SLA-garanti",
    ],
  },
] as const;

export const CREDIT_BUNDLE_PACKAGES = [
  {
    id: "starter_10",
    name: "Starter Pack",
    credits: 10,
    priceInDKK: 5000,
    priceInCents: 500000,
    stripePriceId: process.env.STRIPE_CREDITS_10_PRICE_ID,
  },
  {
    id: "pro_25",
    name: "Pro Pack",
    credits: 25,
    priceInDKK: 10000,
    priceInCents: 1000000,
    discount: 20,
    popular: true,
    stripePriceId: process.env.STRIPE_CREDITS_25_PRICE_ID,
  },
  {
    id: "business_50",
    name: "Business Pack",
    credits: 50,
    priceInDKK: 18000,
    priceInCents: 1800000,
    discount: 28,
    stripePriceId: process.env.STRIPE_CREDITS_50_PRICE_ID,
  },
  {
    id: "enterprise_100",
    name: "Enterprise Pack",
    credits: 100,
    priceInDKK: 30000,
    priceInCents: 3000000,
    discount: 40,
    stripePriceId: process.env.STRIPE_CREDITS_100_PRICE_ID,
  },
] as const;
