import { Candidate } from '../types';
import { ToastType } from '../components/ToastNotification';

export const handleShareProfile = async (
    candidate: Candidate,
    addToast: (type: ToastType, message: string) => void
) => {
    const shareText = `
📋 CANDIDATE PROFILE: ${candidate.name}

🎯 ALIGNMENT SCORE: ${candidate.alignmentScore}%
💼 CURRENT ROLE: ${candidate.currentRole || 'N/A'} at ${candidate.company || 'N/A'}
📍 LOCATION: ${candidate.location || 'N/A'}
📊 EXPERIENCE: ${candidate.yearsExperience || 0} years

${candidate.shortlistSummary ? `📝 SUMMARY:\n${candidate.shortlistSummary}\n` : ''}
${candidate.keyEvidence && candidate.keyEvidence.length > 0 ? `\n✅ KEY STRENGTHS:\n${candidate.keyEvidence.map(e => `• ${e}`).join('\n')}\n` : ''}
${candidate.risks && candidate.risks.length > 0 ? `\n⚠️ CONSIDERATIONS:\n${candidate.risks.map(r => `• ${r}`).join('\n')}\n` : ''}
${candidate.deepAnalysis ? `\n🔍 DEEP ANALYSIS:\n${candidate.deepAnalysis}\n` : ''}
---
Generated by 6Degrees Recruitment OS
    `.trim();

    try {
        if (navigator.share) {
            await navigator.share({
                title: `Profile: ${candidate.name}`,
                text: shareText
            });
            addToast('success', 'Profile shared successfully');
        } else {
            await navigator.clipboard.writeText(shareText);
            addToast('success', 'Profile copied to clipboard');
        }
    } catch (error) {
        console.error('Share error:', error);
        addToast('error', 'Failed to share profile');
    }
};

export const handleDownloadProfilePDF = (
    candidate: Candidate,
    addToast: (type: ToastType, message: string) => void
) => {
    const printContent = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>${candidate.name} - Profile</title>
    <style>
        @media print {
            @page { margin: 2cm; }
        }
        body { font-family: sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
        .header { border-bottom: 3px solid #059669; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { color: #059669; margin: 0 0 10px 0; }
        .score { font-size: 48px; font-weight: bold; color: #059669; margin: 20px 0; }
        .section { margin: 30px 0; page-break-inside: avoid; }
        .section h2 { color: #059669; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; margin-bottom: 15px; }
        .meta { display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 20px 0; }
        .meta-item { padding: 10px; background: #f9fafb; border-left: 3px solid #059669; }
        .meta-label { font-size: 12px; color: #6b7280; text-transform: uppercase; font-weight: 600; }
        .meta-value { font-size: 14px; color: #111827; margin-top: 4px; }
        .footer { margin-top: 50px; padding-top: 20px; border-top: 2px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>${candidate.name}</h1>
        <div class="score">${candidate.alignmentScore}% Match</div>
    </div>
    <div class="section">
        <h2>📊 Profile Overview</h2>
        <div class="meta">
            <div class="meta-item">
                <div class="meta-label">Current Role</div>
                <div class="meta-value">${candidate.currentRole || 'Not specified'}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Company</div>
                <div class="meta-value">${candidate.company || 'Not specified'}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Location</div>
                <div class="meta-value">${candidate.location || 'Not specified'}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Experience</div>
                <div class="meta-value">${candidate.yearsExperience || 0} years</div>
            </div>
        </div>
    </div>
    ${candidate.shortlistSummary ? `<div class="section"><h2>📝 Executive Summary</h2><p>${candidate.shortlistSummary}</p></div>` : ''}
    ${candidate.keyEvidence && candidate.keyEvidence.length > 0 ? `<div class="section"><h2>✅ Key Strengths</h2>${candidate.keyEvidence.map(e => `<div class="list-item">• ${e}</div>`).join('')}</div>` : ''}
    ${candidate.risks && candidate.risks.length > 0 ? `<div class="section"><h2>⚠️ Considerations</h2>${candidate.risks.map(r => `<div class="list-item">• ${r}</div>`).join('')}</div>` : ''}
    <div class="footer">
        <p>Generated by 6Degrees Recruitment OS</p>
        <p>Report generated on ${new Date().toLocaleDateString()}</p>
    </div>
</body>
</html>`;

    const blob = new Blob([printContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${candidate.name.replace(/\s+/g, '_')}_Profile.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    addToast('success', 'Profile downloaded - open in browser to print as PDF');
};
