#!/usr/bin/env ts-node
/**
 * Demo Reset Script
 * 
 * Resets demo environment to a clean state:
 * - Clears localStorage
 * - Resets demo user credentials
 * - Reloads sample data
 * - Verifies test credentials work
 * 
 * Usage:
 *   npm run demo:reset
 *   ts-node scripts/reset-demo.ts
 */

import fs from 'fs';
import path from 'path';

interface DemoConfig {
  users: Array<{
    email: string;
    password: string;
    role: string;
  }>;
  sampleData: {
    candidates: number;
    workflows: number;
    templates: number;
  };
}

const DEMO_CONFIG: DemoConfig = {
  users: [
    {
      email: "demo@recruitos.com",
      password: "demo123",
      role: "admin"
    },
    {
      email: "viewer@recruitos.com",
      password: "demo123",
      role: "viewer"
    }
  ],
  sampleData: {
    candidates: 5,
    workflows: 3,
    templates: 4
  }
};

async function resetDemo() {
  console.log("🔄 Resetting demo environment...\n");

  // Step 1: Clear any existing demo data files
  console.log("📁 Clearing demo data files...");
  const demoDataPath = path.join(__dirname, "../.data/demo");
  
  if (fs.existsSync(demoDataPath)) {
    fs.rmSync(demoDataPath, { recursive: true, force: true });
    console.log("   ✅ Demo data cleared");
  }
  
  fs.mkdirSync(demoDataPath, { recursive: true });

  // Step 2: Generate sample data
  console.log("\n📊 Generating sample data...");
  
  const sampleCandidates = Array.from({ length: DEMO_CONFIG.sampleData.candidates }, (_, i) => ({
    id: `demo-candidate-${i + 1}`,
    name: `Demo Candidate ${i + 1}`,
    email: `candidate${i + 1}@example.com`,
    status: i === 0 ? "active" : "pending",
    score: Math.floor(Math.random() * 40) + 60, // 60-100
    createdAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString()
  }));

  const sampleWorkflows = Array.from({ length: DEMO_CONFIG.sampleData.workflows }, (_, i) => ({
    id: `demo-workflow-${i + 1}`,
    name: `Demo Workflow ${i + 1}`,
    status: "active",
    stages: ["Screen", "Interview", "Offer"]
  }));

  const sampleTemplates = Array.from({ length: DEMO_CONFIG.sampleData.templates }, (_, i) => ({
    id: `demo-template-${i + 1}`,
    name: `Demo Template ${i + 1}`,
    type: ["email", "linkedin", "github"][i % 3],
    content: `This is demo template ${i + 1}`
  }));

  // Step 3: Write sample data
  fs.writeFileSync(
    path.join(demoDataPath, "candidates.json"),
    JSON.stringify(sampleCandidates, null, 2)
  );
  console.log(`   ✅ Created ${sampleCandidates.length} sample candidates`);

  fs.writeFileSync(
    path.join(demoDataPath, "workflows.json"),
    JSON.stringify(sampleWorkflows, null, 2)
  );
  console.log(`   ✅ Created ${sampleWorkflows.length} sample workflows`);

  fs.writeFileSync(
    path.join(demoDataPath, "templates.json"),
    JSON.stringify(sampleTemplates, null, 2)
  );
  console.log(`   ✅ Created ${sampleTemplates.length} sample templates`);

  // Step 4: Verify demo credentials
  console.log("\n🔐 Demo Credentials:");
  DEMO_CONFIG.users.forEach(user => {
    console.log(`   📧 ${user.email} / ${user.password} (${user.role})`);
  });

  // Step 5: Generate .env.demo file
  console.log("\n⚙️  Generating .env.demo...");
  const envDemo = `# Demo Environment Configuration
# Auto-generated by reset-demo.ts

NEXT_PUBLIC_DEMO_MODE=true
NEXT_PUBLIC_DEMO_EMAIL=${DEMO_CONFIG.users[0].email}
NEXT_PUBLIC_DEMO_PASSWORD=${DEMO_CONFIG.users[0].password}

# Feature Flags
NEXT_PUBLIC_ENABLE_ANALYTICS=false
NEXT_PUBLIC_ENABLE_PAYMENTS=false
NEXT_PUBLIC_ENABLE_AI_FEATURES=true
`;

  fs.writeFileSync(path.join(__dirname, "../.env.demo"), envDemo);
  console.log("   ✅ .env.demo created");

  // Success summary
  console.log("\n✅ Demo reset complete!");
  console.log("\n📝 Next steps:");
  console.log("   1. Copy .env.demo to .env.local if needed");
  console.log("   2. Restart dev server: npm run dev");
  console.log("   3. Navigate to: http://localhost:3000?demo=true");
  console.log(`   4. Login with: ${DEMO_CONFIG.users[0].email} / ${DEMO_CONFIG.users[0].password}`);
  console.log("\n🎯 Demo URL: http://localhost:3000?demo=true\n");
}

// Run if executed directly
if (require.main === module) {
  resetDemo().catch(console.error);
}

export { resetDemo, DEMO_CONFIG };
